#
# TPIX Master Node — Windows Installer
# ======================================
# Installs and configures TPIX Master Node on Windows Server
#
# Usage (PowerShell as Administrator):
#   irm https://raw.githubusercontent.com/xjanova/TPIX-Coin/main/masternode/scripts/install.ps1 | iex
#
# Or with options:
#   .\install.ps1 -Tier sentinel -Wallet "0xYourAddress" -Name "my-node"
#

param(
    [ValidateSet("validator", "sentinel", "light")]
    [string]$Tier = "light",

    [string]$Wallet = "",
    [string]$Name = "",
    [switch]$Help
)

$ErrorActionPreference = "Stop"
$TPIX_VERSION = "1.0.0"
$INSTALL_DIR = "$env:ProgramFiles\TPIX Node"
$DATA_DIR = "$env:USERPROFILE\.tpix-node"
$SERVICE_NAME = "TPIXNode"
$GITHUB_REPO = "xjanova/TPIX-Coin"

function Show-Banner {
    Write-Host ""
    Write-Host "  ══════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "    TPIX Master Node Installer v$TPIX_VERSION" -ForegroundColor Cyan
    Write-Host "    https://tpix.online" -ForegroundColor DarkCyan
    Write-Host "  ══════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
}

function Show-Help {
    Write-Host "TPIX Master Node Installer v$TPIX_VERSION"
    Write-Host ""
    Write-Host "Usage: .\install.ps1 [OPTIONS]"
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -Tier TYPE      Node tier: validator, sentinel, light (default: light)"
    Write-Host "  -Wallet ADDR    Your TPIX wallet address (0x...)"
    Write-Host "  -Name NAME      Node display name"
    Write-Host ""
    Write-Host "Tiers:"
    Write-Host "  validator  1,000,000 TPIX stake  12-15% APY  (max 100 nodes)" -ForegroundColor Yellow
    Write-Host "  sentinel     100,000 TPIX stake   7-10% APY  (max 500 nodes)" -ForegroundColor Magenta
    Write-Host "  light         10,000 TPIX stake    4-6% APY  (unlimited)"     -ForegroundColor Cyan
}

function Log-Info  { param([string]$msg) Write-Host "  [OK]    $msg" -ForegroundColor Green }
function Log-Warn  { param([string]$msg) Write-Host "  [WARN]  $msg" -ForegroundColor Yellow }
function Log-Error { param([string]$msg) Write-Host "  [ERROR] $msg" -ForegroundColor Red }

function Check-Admin {
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        Log-Error "Please run this script as Administrator"
        Log-Info  "Right-click PowerShell -> Run as Administrator"
        exit 1
    }
}

function Check-Requirements {
    Log-Info "Checking system requirements..."

    # Check architecture
    $arch = if ([Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }
    Log-Info "OS: Windows / Arch: $arch"

    # Check memory
    $totalMem = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1MB)
    Log-Info "Total Memory: ${totalMem}MB"

    switch ($Tier) {
        "validator" {
            if ($totalMem -lt 14000) {
                Log-Warn "Validator nodes recommend 16GB RAM (found ${totalMem}MB)"
            }
        }
        "sentinel" {
            if ($totalMem -lt 6000) {
                Log-Warn "Sentinel nodes recommend 8GB RAM (found ${totalMem}MB)"
            }
        }
    }

    Log-Info "Requirements OK"
}

function Download-Binary {
    Log-Info "Downloading TPIX Node v$TPIX_VERSION..."

    $url = "https://github.com/$GITHUB_REPO/releases/download/v$TPIX_VERSION/tpix-node-windows-amd64.zip"
    $zipPath = "$env:TEMP\tpix-node.zip"

    # Create install directory
    New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null

    try {
        Invoke-WebRequest -Uri $url -OutFile $zipPath -UseBasicParsing
        Expand-Archive -Path $zipPath -DestinationPath $INSTALL_DIR -Force
        Remove-Item $zipPath
        Log-Info "Binary installed to $INSTALL_DIR\tpix-node.exe"
    } catch {
        Log-Warn "Could not download pre-built binary."
        Log-Info "Please build from source or download manually from:"
        Log-Info "  https://github.com/$GITHUB_REPO/releases"
    }
}

function Configure-Node {
    Log-Info "Configuring node..."

    # Create data directories
    @("$DATA_DIR", "$DATA_DIR\logs", "$DATA_DIR\data", "$DATA_DIR\keystore") | ForEach-Object {
        New-Item -ItemType Directory -Path $_ -Force | Out-Null
    }

    # Generate config
    $configPath = "$DATA_DIR\tpix-node.yaml"

    $config = @"
# TPIX Master Node Configuration
# Generated by installer v$TPIX_VERSION

node_name: "$( if ($Name) { $Name } else { "tpix-node-$(Get-Random -Maximum 9999)" } )"
tier: "$Tier"
wallet_address: "$Wallet"
keystore_path: "$DATA_DIR\keystore"

chain_rpc: "https://rpc.tpix.online"
chain_id: 4289

p2p_port: 30303
rpc_port: 8545
dashboard_port: 3847

data_dir: "$DATA_DIR"
max_peers: 50
sync_mode: "full"
enable_metrics: true
metrics_port: 9090

log_level: "info"
log_file: "$DATA_DIR\logs\node.log"

auto_update: true
update_channel: "stable"
"@

    $config | Out-File -FilePath $configPath -Encoding utf8
    Log-Info "Configuration saved to $configPath"
}

function Install-Service {
    Log-Info "Installing Windows service..."

    # Add to PATH
    $envPath = [Environment]::GetEnvironmentVariable("PATH", "Machine")
    if ($envPath -notlike "*$INSTALL_DIR*") {
        [Environment]::SetEnvironmentVariable("PATH", "$envPath;$INSTALL_DIR", "Machine")
    }

    # Create Windows Service using sc.exe
    $exePath = "$INSTALL_DIR\tpix-node.exe"
    $configPath = "$DATA_DIR\tpix-node.yaml"

    # Remove existing service if any
    sc.exe query $SERVICE_NAME 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
        sc.exe stop $SERVICE_NAME 2>$null | Out-Null
        sc.exe delete $SERVICE_NAME 2>$null | Out-Null
        Start-Sleep -Seconds 2
    }

    # Create new service
    sc.exe create $SERVICE_NAME `
        binPath= "`"$exePath`" --config=`"$configPath`"" `
        DisplayName= "TPIX Master Node" `
        start= auto `
        obj= "NT AUTHORITY\NetworkService" | Out-Null

    sc.exe description $SERVICE_NAME "TPIX Blockchain Master Node - Validates transactions and earns rewards" | Out-Null

    # Configure recovery (restart on failure)
    sc.exe failure $SERVICE_NAME reset= 86400 actions= restart/10000/restart/30000/restart/60000 | Out-Null

    # Open firewall ports
    netsh advfirewall firewall add rule name="TPIX Node P2P" dir=in action=allow protocol=tcp localport=30303 | Out-Null
    netsh advfirewall firewall add rule name="TPIX Node Dashboard" dir=in action=allow protocol=tcp localport=3847 | Out-Null

    Log-Info "Service installed: $SERVICE_NAME"
}

function Start-Node {
    Log-Info "Starting TPIX Master Node..."

    sc.exe start $SERVICE_NAME | Out-Null
    Start-Sleep -Seconds 3

    $status = sc.exe query $SERVICE_NAME | Select-String "RUNNING"
    if ($status) {
        Log-Info "Node is running!"
    } else {
        Log-Warn "Service may still be starting. Check: sc.exe query $SERVICE_NAME"
    }
}

function Show-Summary {
    Write-Host ""
    Write-Host "  ══════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "    TPIX Master Node - Installation Complete!" -ForegroundColor Green
    Write-Host "  ══════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Tier:       $Tier" -ForegroundColor White
    Write-Host "  Wallet:     $(if ($Wallet) { $Wallet } else { '(not set - edit config)' })" -ForegroundColor White
    Write-Host "  Config:     $DATA_DIR\tpix-node.yaml" -ForegroundColor White
    Write-Host "  Dashboard:  http://localhost:3847" -ForegroundColor Cyan
    Write-Host "  Logs:       $DATA_DIR\logs\node.log" -ForegroundColor White
    Write-Host ""
    Write-Host "  Commands:" -ForegroundColor Yellow
    Write-Host "    tpix-node status                Show node status"
    Write-Host "    tpix-node dashboard             Open web dashboard"
    Write-Host "    sc.exe stop $SERVICE_NAME            Stop node"
    Write-Host "    sc.exe start $SERVICE_NAME           Start node"
    Write-Host ""

    if (-not $Wallet) {
        Write-Host "  IMPORTANT:" -ForegroundColor Yellow
        Write-Host "  Set your wallet address in $DATA_DIR\tpix-node.yaml"
        Write-Host "  Then restart: sc.exe stop $SERVICE_NAME && sc.exe start $SERVICE_NAME"
        Write-Host ""
    }

    Write-Host "  Stake TPIX at: https://tpix.online/masternode" -ForegroundColor Cyan
    Write-Host ""
}

# ============================================================
#  Main
# ============================================================

if ($Help) { Show-Help; exit 0 }

Show-Banner
Check-Admin
Check-Requirements
Download-Binary
Configure-Node
Install-Service
Start-Node
Show-Summary
